#!/usr/bin/env sh
MAINDIR=$(pwd)
make julia-base -j10
make julia-deps -j10
gcc -c $MAINDIR/cli-static/static_exe.c -o $MAINDIR/cli-static/static_exe.o
make julia-src-release -j10
make julia-stdlib -j10
mkdir usr/staticlibs

cd src
ar rcs $MAINDIR/usr/staticlibs/libjulia-internal.a ./jltypes.o ./gf.o ./typemap.o ./smallintset.o ./ast.o ./builtins.o ./module.o ./interpreter.o ./symbol.o ./dlload.o ./sys.o ./init.o ./task.o ./array.o ./staticdata.o ./toplevel.o ./jl_uv.o ./datatype.o ./simplevector.o ./runtime_intrinsics.o ./precompile.o ./jloptions.o ./threading.o ./partr.o ./stackwalk.o ./gc.o ./gc-debug.o ./gc-pages.o ./gc-stacks.o ./gc-alloc-profiler.o ./method.o ./jlapi.o ./signal-handling.o ./safepoint.o ./timing.o ./subtype.o ./rtutils.o ./gc-heap-snapshot.o ./crc32c.o ./APInt-C.o ./processor.o ./ircode.o ./opaque_closure.o ./codegen-stubs.o ./coverage.o ./runtime_ccall.o
ar rcs $MAINDIR/usr/staticlibs/libjulia-codegen.a ./codegen.o ./jitlayers.o ./aotcompile.o ./debuginfo.o ./disasm.o ./llvm-simdloop.o ./llvm-muladd.o ./llvm-final-gc-lowering.o ./llvm-pass-helpers.o ./llvm-late-gc-lowering.o ./llvm-ptls.o ./llvm-lower-handlers.o ./llvm-gc-invariant-verifier.o ./llvm-propagate-addrspaces.o ./llvm-multiversioning.o ./llvm-alloc-opt.o ./llvm-alloc-helpers.o ./cgmemmgr.o ./llvm-remove-addrspaces.o ./llvm-remove-ni.o ./llvm-julia-licm.o ./llvm-demote-float16.o ./llvm-cpufeatures.o ./pipeline.o
cd ..
cp $MAINDIR/cli-static/static_exe.o $MAINDIR/usr/staticlibs/
cp $MAINDIR/usr/lib/*.a $MAINDIR/usr/staticlibs/
cp $MAINDIR/src/flisp/libflisp.a $MAINDIR/usr/staticlibs/
cp $MAINDIR/src/support/libsupport.a $MAINDIR/usr/staticlibs/
rm $MAINDIR/usr/lib/libjulia*
gcc -m64 -std=gnu11 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64  -I$MAINDIR/src -I$MAINDIR/src/support -I$MAINDIR/usr/include -ffreestanding -O3 -ggdb2 -falign-functions -momit-leaf-frame-pointer $MAINDIR/usr/staticlibs/static_exe.o -o $MAINDIR/usr/bin/julia -Wl,-Bdynamic -Wl,-no-undefined -ffreestanding  -L$MAINDIR/usr/staticlibs -Wl,--whole-archive -ljulia-internal -ljulia-codegen -lsupport -luv -lutf8proc -lflisp -Wl,--export-dynamic,--as-needed,--no-whole-archive -Wl,-rpath,$MAINDIR/usr/lib -Wl,-rpath,$MAINDIR -Wl,-rpath-link,$MAINDIR/usr/lib -lLLVMWindowsManifest -lLLVMXRay -lLLVMLibDriver -lLLVMDlltoolDriver -lLLVMCoverage -lLLVMLineEditor -lLLVMX86TargetMCA -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Info -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo  -lLLVMBPFDisassembler -lLLVMBPFAsmParser -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo  -lLLVMAMDGPUTargetMCA -lLLVMAMDGPUDisassembler -lLLVMAMDGPUAsmParser -lLLVMAMDGPUCodeGen -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMIntelJITEvents -lLLVMPerfJITEvents -lLLVMOrcJIT -lLLVMMCJIT -lLLVMJITLink -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMOrcTargetProcess -lLLVMOrcShared -lLLVMDWP -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoGSYM -lLLVMOption -lLLVMObjectYAML -lLLVMMCA -lLLVMMCDisassembler -lLLVMLTO -lLLVMCFGuard -lLLVMFrontendOpenACC -lLLVMExtensions -lLLVMPasses -lLLVMObjCARCOpts -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMFrontendOpenMP -lLLVMDWARFLinker -lLLVMGlobalISel -lLLVMMIRParser -lLLVMAsmPrinter -lLLVMDebugInfoMSF -lLLVMSelectionDAG -lLLVMCodeGen -lLLVMIRReader -lLLVMAsmParser -lLLVMInterfaceStub -lLLVMFileCheck -lLLVMFuzzMutate -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMDebugInfoDWARF -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMBitReader -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMBinaryFormat -lLLVMTableGen -lLLVMSupport -lLLVMDemangle -lopenlibm --std=c++14 -lstdc++ -lunwind -lrt -ldl -lpthread -lm -lz -latomic -rdynamic -lc
JULIA_EXE=$MAINDIR/usr/bin/julia
SYSIMG_DIR=$MAINDIR/usr/lib/julia
cd $MAINDIR/base
$JULIA_EXE -C "native" --output-ji $SYSIMG_DIR/corecompiler.ji --startup-file=no --warn-overwrite=yes  -g0 -O0 compiler/compiler.jl
$JULIA_EXE -g1 -O0 -C "native" --output-ji $SYSIMG_DIR/sys.ji  --startup-file=no --warn-overwrite=yes  --sysimage $SYSIMG_DIR/corecompiler.ji sysimg.jl
JULIA_NUM_THREADS=1  $JULIA_EXE -O3 -C "native" --output-o $SYSIMG_DIR/sys-o.a --startup-file=no --warn-overwrite=yes --pkgimages=no --sysimage $SYSIMG_DIR/sys.ji $MAINDIR/contrib/generate_precompile.jl
cd $MAINDIR
gcc -m64 -std=gnu11 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64  -I$MAINDIR/src -I$MAINDIR/src/support -I$MAINDIR/usr/include -ffreestanding -O3 -ggdb2 -falign-functions -momit-leaf-frame-pointer $MAINDIR/usr/staticlibs/static_exe.o -o $MAINDIR/usr/bin/julia -Wl,-Bdynamic -Wl,-no-undefined -ffreestanding  -L$MAINDIR/usr/staticlibs -Wl,--whole-archive $SYSIMG_DIR/sys-o.a -ljulia-internal -ljulia-codegen -lsupport -luv -lutf8proc -lflisp -Wl,--export-dynamic,--as-needed,--no-whole-archive -Wl,-rpath,$MAINDIR/usr/lib -Wl,-rpath,$MAINDIR -Wl,-rpath-link,$MAINDIR/usr/lib -lLLVMWindowsManifest -lLLVMXRay -lLLVMLibDriver -lLLVMDlltoolDriver -lLLVMCoverage -lLLVMLineEditor -lLLVMX86TargetMCA -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Info -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo  -lLLVMBPFDisassembler -lLLVMBPFAsmParser -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo  -lLLVMAMDGPUTargetMCA -lLLVMAMDGPUDisassembler -lLLVMAMDGPUAsmParser -lLLVMAMDGPUCodeGen -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMIntelJITEvents -lLLVMPerfJITEvents -lLLVMOrcJIT -lLLVMMCJIT -lLLVMJITLink -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMOrcTargetProcess -lLLVMOrcShared -lLLVMDWP -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoGSYM -lLLVMOption -lLLVMObjectYAML -lLLVMMCA -lLLVMMCDisassembler -lLLVMLTO -lLLVMCFGuard -lLLVMFrontendOpenACC -lLLVMExtensions -lLLVMPasses -lLLVMObjCARCOpts -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMFrontendOpenMP -lLLVMDWARFLinker -lLLVMGlobalISel -lLLVMMIRParser -lLLVMAsmPrinter -lLLVMDebugInfoMSF -lLLVMSelectionDAG -lLLVMCodeGen -lLLVMIRReader -lLLVMAsmParser -lLLVMInterfaceStub -lLLVMFileCheck -lLLVMFuzzMutate -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMDebugInfoDWARF -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMBitReader -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMBinaryFormat -lLLVMTableGen -lLLVMSupport -lLLVMDemangle -lopenlibm --std=c++14 -lstdc++ -lunwind -lrt -ldl -lpthread -lm -lz -latomic -rdynamic -lc